spring:
  application:
    name: test-kafka-ssl
  kafka:
    bootstrap-servers: localhost:9093
    security:
      protocol: SSL
    ssl:
      key-store-location: classpath:kafka.client.keystore.jks
      key-store-password: changeit
      key-password: changeit
      trust-store-location: classpath:kafka.client.truststore.jks
      trust-store-password: changeit
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer